"""empty message

Revision ID: a8e00fafa389
Revises: 
Create Date: 2022-03-15 17:21:12.205179

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a8e00fafa389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humidity',
                    sa.Column('id', sa.INTEGER(), autoincrement=True,
                              nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('value', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('temperature',
                    sa.Column('id', sa.INTEGER(), autoincrement=True,
                              nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('value', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature')
    op.drop_table('humidity')
    # ### end Alembic commands ###
