"""empty message

Revision ID: b3fda6888938
Revises: a8e00fafa389
Create Date: 2022-03-18 20:05:33.336865

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b3fda6888938'
down_revision = 'a8e00fafa389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
                    sa.Column('id', sa.INTEGER(), autoincrement=True,
                              nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('temperature', sa.Float(), nullable=False),
                    sa.Column('humidity', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('humidity')
    op.drop_table('temperature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('timestamp', sa.DATETIME(), nullable=False),
                    sa.Column('value', sa.FLOAT(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('humidity',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('timestamp', sa.DATETIME(), nullable=False),
                    sa.Column('value', sa.FLOAT(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('measurement')
    # ### end Alembic commands ###
